title: Fan's HomePage
email: Fan_Yang@sjtu.edu.cn
description: >-
baseurl: ""
url: "https://raphus-cucullatus.github.io"
github_username: Raphus-cucullatus
rss: rss

disqus:
    shortname: homepage-ni6rifkb5r

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
