#+TITLE: Introducing ivy-cscope.el, using cscope in Emacs with ivy completion!
#+DATE: May 20, 2020

** Introduction

*[[https://github.com/Raphus-cucullatus/ivy-cscope.el][ivy-cscope.el]]* is yet another interface for [[http://cscope.sourceforge.net][cscope]] in Emacs.

Compared with other cscope package in Emacs, It features using [[https://github.com/abo-abo/swiper][ivy]] to display and select the cscope jump candidates.  It also uses "ivy actions" to perform rich actions (e.g. open other window, open other window without focus) on the jump candidates.

It provides
- ~ivy-cscope-find-xxx~: 9 functions each for cscope's menu (e.g. symbol, definition, assignment, calling, ...).
- ~ivy-cscope-find-definition-at-point~: a handy command to find the definition of the symbol at point.
- ~ivy-cscope-pop-mark~: jump back to the location before the last ~ivy-cscope-xxxx~ jump.
- ~ivy-cscope-command-map~: a keymap of all the commands above.

** Example usage:

*** You can bind the key map by:

#+begin_src emacs-lisp
  (define-key c-mode-base-map (kbd "C-c j c") ivy-cscope-command-map)
#+end_src

*** Also for quick access:

#+begin_src emacs-lisp
  (define-key c-mode-base-map (kbd "M-.") 'ivy-cscope-find-definition-at-point)
  (define-key c-mode-base-map (kbd "M-,") 'ivy-cscope-pop-mark)
  (define-key c-mode-base-map [M-mouse-1] 'ivy-cscope-find-definition-at-point)
  (define-key c-mode-base-map [M-S-mouse-1] 'ivy-cscope-pop-mark)
#+end_src

*** Get familiar with ivy actions:

1. Press ~C-c j c c~ (or ~M-x ivy-cscope-find-caller~).
2. Insert ~put_user_pages~ to find functions calling ~put_user_pages~.
3. A completion list shows up, like

   #+begin_src
       (1/3) Result:
       drivers/infiniband/core/umem_odp.c ...
       fs/io_uring.c ...
       mm/gup.c ...
   #+end_src

4. Move to some line and press ~M-o~ to trigger ivy actions.  A list of actions are shown, for example, open the result in other window, open the result in other window without focus, ....
 
*** Other hints when using ivy completion (not directly related to this package)

If you use [[https://github.com/abo-abo/avy][avy]], you can bind ~ivy-avy~ so that you can jump to a specific result with a single key stroke:

#+begin_src emacs-lisp
  (define-key ivy-minibuffer-map (kbd "M-'") 'ivy-avy)
#+end_src

When in ivy minibuffer, one can use 
- ~C-M-m~ to preview the current candidate (select the candidate while remain the point in the minibuffer).
- ~C-M-n~ to preview the next candidate.
- ~C-M-p~ to preview the previous candidate.
- ~C-g~ to abort the preview.

** Other Emacs cscope packages:

- [[https://github.com/dkogan/xcscope.el][xcscope.el]].

