#+TITLE: QEMU: Adding a New Trace Event
#+DATE: Jul 09, 2019

For example, I want to add three trace functions in
~migration/migration.c~:
#+BEGIN_EXAMPLE
trace_migration_completion_wakeup_request();
trace_migration_completion_globalstate_store();
trace_migration_completion_vm_stop();
#+END_EXAMPLE

The steps are as follows.

* Locate corresponding trace events file  
First, find the ~trace-events~ file in the sub-directory where your
modification is going to happen.  Here, it is
~migration/trace-events~.
* Specify trace events
Then, append one line for each trace function.  The line specifies the
trace function name, its args and print formatting.  In my case, they
are
#+BEGIN_EXAMPLE
migration_completion_wakeup_request(void) ""
migration_completion_globalstate_store(void) ""
migration_completion_vm_stop(void) ""
#+END_EXAMPLE
* Place your trace function
Now place the trace functions where you want.
* Build and run
Note that tracing should be enabled with a backend and switched on.
When ~./configure~, add
#+BEGIN_SRC
--enable-trace-backends=<choose your tracing backends>
#+END_SRC
Check ~/.configure --help~ for supported tracing backends.

And when run QEMU, add
#+BEGIN_SRC
-trace events=<file that contains events you want to trace>
#+END_SRC
* Troubleshooting
** "implicit declaration of function '~trace_xxx~' "?
This is possibly due to not including "~trace.h~".  QEMU generates the
implementation of the trace functions for you according to the
~trace-events~ files in ~trace.c~ files, as well as the declarations
in ~trace.h~ files.  Many "~.c~" files have already included
"~trace.h~".  If not, include it yourself.  One exception is for adding
trace events at the QEMU source root directory.  In this case, include
"~trace-root.h~".
** "trace-events does not end with a new line"?
Currently all the ~trace-events~ files should be ended with a new
line.  Otherwise error would be reported when parsing and when at run
time.
** "warning: trace event 'abc' does not exist"?
If you get this error while the trace event is actually named 'abcd',
it is likely the same reason as the issue above.  An ending new line
is required in the ~trace-events~ files.
* See also
For more details on QEMU tracing, see ~docs/devel/tracing.txt~ in the
QEMU repository.
